### ISSUE TITLE
Error when trying to extract.

### ISSUE THREAD

**Issue by ismailmayat** [KevM/tikaondotnet#100]
When i try to extract pdf or word (only test those so far) I get the following error:
```TikaOnDotNet.TextExtraction.TextExtractionException: Extraction failed. ---> javax.xml.transform.TransformerFactoryConfigurationError: Provider com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl not found
   at javax.xml.transform.FactoryFinder.newInstance(Class , String , ClassLoader , Boolean , Boolean )
   at javax.xml.transform.FactoryFinder.find(Class , String )
   at javax.xml.transform.TransformerFactory.newInstance()
   at TikaOnDotNet.TextExtraction.Stream.StreamTextExtractor.GetTransformerHandler(Stream outputStream) in C:\projects\tikaondotnet\src\TikaOnDotnet.TextExtractor\Stream\StreamTextExtractor.cs:line 49
   at TikaOnDotNet.TextExtraction.Stream.StreamTextExtractor.Extract(Func`2 streamFactory, Stream outputStream) in C:\projects\tikaondotnet\src\TikaOnDotnet.TextExtractor\Stream\StreamTextExtractor.cs:line 21
   --- End of inner exception stack trace ---
   at TikaOnDotNet.TextExtraction.Stream.StreamTextExtractor.Extract(Func`2 streamFactory, Stream outputStream) in C:\projects\tikaondotnet\src\TikaOnDotnet.TextExtractor\Stream\StreamTextExtractor.cs:line 43
   at TikaOnDotNet.TextExtraction.TextExtractor.Extract(Func`2 streamFactory) in C:\projects\tikaondotnet\src\TikaOnDotnet.TextExtractor\TextExtractor.cs:line 53
   at TikaOnDotNet.TextExtraction.TextExtractor.Extract(String filePath) in C:\projects\tikaondotnet\src\TikaOnDotnet.TextExtractor\TextExtractor.cs:line 19
   --- End of inner exception stack trace ---
   at TikaOnDotNet.TextExtraction.TextExtractor.Extract(String filePath) in C:\projects\tikaondotnet\src\TikaOnDotnet.TextExtractor\TextExtractor.cs:line 28
```

Am i missing something? I installed via nuget

**Comment by KevM** [comment]
Let me know if you have a test or file we can try to duplicate this.
