### ISSUE TITLE
TikaOnDotNet crashes on one machine, but not another

### ISSUE THREAD

**Issue by zackeezy** [KevM/tikaondotnet#135]
I am trying to extract text from a PDF.  On my machine where I compiled the DLL, it runs and extracts perfectly, but when I move it to another machine where it is meant to live, it errors out with the following error:

    6/14/2019 2:00:08 PM
    The program encountered unexpected behavior with this file. Moving to error folder.
    Error information: 
    Extraction of text from the file 'C:\path\to\pdf\file\350143_06142019_15400.pdf' failed.
    Stack Trace: 
       at TikaOnDotNet.TextExtraction.TextExtractor.Extract[TExtractionResult](String filePath, Func`3 extractionResultAssembler)
       at DowGPCCalibration_FileProcessor_vAPI.FileProcessor.ParseFile(FileInfo fileInfo)
       at File_Processor.mainForm.uploaderThread_DoWork(Object sender, DoWorkEventArgs e) in 
    D:\path\to\cs\file\MainForm.cs:line 539

I'm not sure what could be causing this.  Is it a missing dependency? The machines are in a lab so the less I can go back and forth for testing the better. lol

**Comment by KevM** [comment]
Likely you are not distributing all of the IKVM dependencies you need.
