### ISSUE TITLE
TextExtractor.Extract fails when run asynchronously

### ISSUE THREAD

**Issue by bravecobra** [KevM/tikaondotnet#29]
When using the Extract Method in an async Task, the method fails with the inner exception message "Thread was being aborted". The stacktrace shows 
``` 
   at java.io.File..ctor(String pathname)
   at TikaOnDotNet.TextExtractor.Extract(String filePath)
```
The method then throws an normal TextExtractionException with the message "Extraction of text from the file '{MyFilename}' failed."

When running the same code synchronously, it works perfectly, however I'd like to do the extraction in a background thread obviously.

**Comment by bravecobra** [comment]
Seemed to be an error on my part, making the thread abort.
