### ISSUE TITLE
TikaOnDotNet.TextExtraction.TextExtractionException: Object reference not set

### ISSUE THREAD

**Issue by jonathan-racicot** [KevM/tikaondotnet#91]
Hello,

Got into a snag using TextExtractor using a URL. I wonder if it's because the URL does not contain an actual file at the end. Any help appreciated. Thanks!

EDIT: Using version 1.14.1

```
...
TextExtractor WebTextExtractor;
TextExtractionResult ExtractionResults;

WebTextExtractor = new TextExtractor();
//FilePath = "https://www.virustotal.com/en/file/a522fb0bd7a614369f1b43afeacf9dcf4fa186d9143142ba90ceb3b10a73c6fa/analysis/"
ExtractionResults = WebTextExtractor.Extract(new Uri(FilePath)); //<- Exception
...
```
This call with the given URL results in this exception:
```
TikaOnDotNet.TextExtraction.TextExtractionException was unhandled
  HResult=-2146233088
  Message=Extraction failed.
  Source=TikaOnDotNet.TextExtraction
  StackTrace:
       at TikaOnDotNet.TextExtraction.Stream.StreamTextExtractor.Extract(Func`2 streamFactory, Stream outputStream) in C:\projects\tikaondotnet\src\TikaOnDotnet.TextExtractor\Stream\StreamTextExtractor.cs:line 41
       at TikaOnDotNet.TextExtraction.TextExtractor.Extract(Func`2 streamFactory) in C:\projects\tikaondotnet\src\TikaOnDotnet.TextExtractor\TextExtractor.cs:line 52
       at TikaOnDotNet.TextExtraction.TextExtractor.Extract(Uri uri) in C:\projects\tikaondotnet\src\TikaOnDotnet.TextExtractor\TextExtractor.cs:line 39
       at deepcode.intel.tachikoma.document.WebDocument.ReadContent() in D:\src\tachikoma\tachikoma.core\unlimited\document\WebDocument.cs:line 35
       at deepcode.intel.tachikoma.core.IndicatorExtractor.ExtractIndicators(IntelligenceDocument IntelDoc, ISet`1 Categories) in D:\src\tachikoma\tachikoma.core\unlimited\core\IExtract.cs:line 102
       at deepcode.intel.tachikoma.Tachikoma.ExtractIndicatorsFromDocument(SourceDocument Document, ISet`1 IndicatorsCategories) in D:\src\tachikoma\tachikoma.core\unlimited\TCore.cs:line 369
       at deepcode.intel.tachikoma.Tachikoma.<>c__DisplayClass9_0.<ExtractIndicatorsFromDocuments>b__0() in D:\src\tachikoma\tachikoma.core\unlimited\TCore.cs:line 121
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
       HResult=-2147467261
       Message=Object reference not set to an instance of an object.
       Source=TikaOnDotNet
       StackTrace:
            at org.apache.tika.mime.MimeTypesFactory.create(String coreFilePath, String extensionFilePath, ClassLoader classLoader)
            at org.apache.tika.mime.MimeTypes.getDefaultMimeTypes(ClassLoader classLoader)
            at org.apache.tika.config.TikaConfig.getDefaultMimeTypes(ClassLoader )
            at org.apache.tika.config.TikaConfig..ctor()
            at org.apache.tika.config.TikaConfig.getDefaultConfig()
            at org.apache.tika.parser.AutoDetectParser..ctor()
            at TikaOnDotNet.TextExtraction.Stream.StreamTextExtractor.Extract(Func`2 streamFactory, Stream outputStream) in C:\projects\tikaondotnet\src\TikaOnDotnet.TextExtractor\Stream\StreamTextExtractor.cs:line 16
       InnerException: 

```

**Comment by KevM** [comment]
I believe the URL extract is not working correctly. There is another issue for this.

**Comment by KevM** [comment]
Checkout the PR #93 which I believe will fix this problem.
